[package]
name = "transys"
version = "0.1.0"
edition = "2021"

[dependencies]
aig = { path = "../aig-rs" }
minisat = { path = "../minisat-rs" }
logic-form = { path = "../logic-form" }
satif = { path = "../satif" }
